### ISSUE TITLE
Include cdn instead of big lib files . 

### ISSUE THREAD

**Issue by lapachuka** [davidrud135/Responsive-Website#11]
for example . You have bootstrap lib with css , js , theme ... so on . Instead of keeping those files you can load all of it from cdn . It will keep your project smaller and it will loads quicker for customer which is good . 

Your issue is to find cdn sources  for all libs.

example of bootstrap cdn . 

`<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">`

`<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">`

`<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>`

**Comment by davidrud135** [comment]
Ready, but I did not include cdn `jquery.bxslider.css` because I applied custom styles in it.

**Comment by lapachuka** [comment]
That is bad solution to put your styles into lib.  That 's why you should load lib's from cdn and `jquery.bxslider.css` too . Move your own logic , style whatever to `YOUR` files !!

**Comment by davidrud135** [comment]
Ready
