### ISSUE TITLE
Зміни таби на 2 ПРОБІЛИ! А не вигляд табів в тебе у IDE

### ISSUE THREAD

**Issue by lapachuka** [davidrud135/Responsive-Website#6]

**Comment by lapachuka** [comment]
Важко орієнтуватись в твому коді на github

**Comment by davidrud135** [comment]
Ok

**Comment by davidrud135** [comment]
Ось так?
![tab_spacing_screen2](https://user-images.githubusercontent.com/25286306/38141718-290ff396-3442-11e8-8bfb-4ed90c99d3da.png)

**Comment by lapachuka** [comment]
"editor.tabSize": 2,

**Comment by davidrud135** [comment]
Так і стояло

**Comment by lapachuka** [comment]
Це не чат . Шукай будь ласка . Треба результат . Постарайся . google + stack owerflow + youtube тобі в допомогу
